# Generated by Django 3.2 on 2021-04-30 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('21', 'Size A4'), ('8', 'Size A5')], default='21', max_length=20)),
                ('speed', models.CharField(default=0, max_length=5)),
                ('state', models.CharField(choices=[('1', 'Start'), ('0', 'Stop')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='data_avg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_line', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='data_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='dut_net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dut_net_length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='pen_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_pen', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dotted_lenght', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('1', 'Bút đạt chuẩn'), ('0', 'Bút Không đạt chuẩn')], max_length=10)),
                ('time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizepaper', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('error', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('1', 'Start'), ('0', 'Stop')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dut_net_error', models.IntegerField(max_length=10)),
                ('mong_net_error', models.IntegerField(max_length=10)),
                ('high_width', models.DecimalField(decimal_places=3, max_digits=8)),
                ('low_width', models.DecimalField(decimal_places=3, max_digits=8)),
                ('length', models.IntegerField(max_length=10)),
            ],
        ),
    ]
