# Generated by Django 3.2 on 2021-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='dut_net_error',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='mong_net_error',
            field=models.IntegerField(),
        ),
    ]
