# Generated by Django 3.2 on 2021-05-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlApp', '0003_filterbyday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
