# Generated by Django 3.2 on 2021-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlApp', '0005_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='speed',
            new_name='distance',
        ),
        migrations.AddField(
            model_name='test',
            name='speedX',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='speedY',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
