# Generated by Django 3.2 on 2021-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlApp', '0007_test_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='speedX',
        ),
        migrations.RemoveField(
            model_name='test',
            name='speedY',
        ),
        migrations.AddField(
            model_name='test',
            name='levelSpeed',
            field=models.CharField(choices=[('1', 'Low speed'), ('2', 'Normal speed'), ('3', 'Fast speed')], default='1', max_length=2),
        ),
    ]
