# Generated by Django 3.2 on 2021-06-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlApp', '0008_auto_20210528_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen_show',
            name='dotted_lenght',
        ),
    ]
